### DISCUSSION TITLE
How do you add this package to a project?

### DISCUSSION THREAD

**Discussion by cdimitroulas** [kowainik/cake-slayer#56] [Q&A] [answered]
Hi there,

I was wondering how do you actually install this framework into a cabal or stack project? I couldn't find cake-slayer on Hackage and there aren't any instructions in this project's README and as a Haskell newbie I wasn't sure how to proceed. Any help would be much appreciated!

**Comment by worm2fed** [comment, marked as answer]
You have two options here.
- make a fork / just copy modules to your project and use as a part of your codebase (do not forget to add license headers)

in case you use stack:
add `cake-slayer` as dependency to your `package.yaml` and add to `stack.yam` 
```
- git: git@github.com:kowainik/cake-slayer.git
   commit: COMMIT_REF
```

in case you use cabal, create `cabal.project`:
```
with-compiler: ghc-VERSION

packages:
    ./

source-repository-package
    type: git
    location: git@github.com:kowainik/cake-slayer.git
    tag: COMMIT_REF
```
